### PR TITLE
added checksum verification for s6 and goss download in Dockerfiles

### PR DESCRIPTION
**Pull request by moritzraho**
verify the integrity of downloaded code in Dockerfiles

### CODE REVIEW

**Comment by moritzraho** [comment]
Hi, anyone ?

**Comment by mayanand** [comment]
cc: ^^^ @mannytoledo @ko-be

**Comment by bryanlatten** [comment]
@moritzraho apologies for the delay - could you upgrade to the latest s6 (3.6) at the same time?

**Comment by bryanlatten** [comment]
and thank you for your contribution!

**Comment by moritzraho** [comment]
@bryanlatten thanks for reviewing this, I've just updated goss and s6 to the latest version

**Comment by moritzraho** [comment]
Oops missed some images, should be fine now also I tested all with test.sh

**Pull request merged**
