### PR TITLE
S6: updated to 2.X version

### PR DESCRIPTION
**Pull request by bryanlatten**

### CODE REVIEW

**Comment by adobejmong** [comment]
Since this is an S6 major version, we should rev to a major on the base BBCs right? Just checking @bryanlatten

**Comment by bryanlatten** [comment]
@adobejmong in all reality, we should plan to wait for a few patch versions on this new major

**Comment by adobejmong** [comment]
@adobejmong : I ran through a number of test cases and a few of our base images and at the very least, it does not look like there were any issues. Also tested with env vars with values >4K each and that all seemed to be fine.

So personally, I think this is OK to merge from my standpoint.

**Comment by bryanlatten** [comment]
@adobejmong do we need to remove the workaround at this point?

**Comment by adobejmong** [comment]
@bryanlatten : I would recommend that we keep the workaround as part of this change to minimize this PR and remove the file as part of a different PR. For folks who still use the script, they might expect those files e.g. if they are sourcing it. Maybe we start adding a deprecated message in a future release and then eventually remove it

**Comment by githubsaritasa** [comment]
Has this got merged into develop and published on the docker hub? Seems that **latest** still has *1.2x* version according to the code.

**Comment by bryanlatten** [comment]
@githubsaritasa they are building out now on docker hub

**Pull request merged**
