### PR TITLE
bumping Ubuntu version to 17.10

### PR DESCRIPTION
**Pull request by mayanand**
Search team is looking for a bump in Ubuntu version. This PR should address it.
@bryanlatten Please review.

### CODE REVIEW

**Comment by bryanlatten** [comment]
Due to the extremely narrow (X.10) support [window](https://www.ubuntu.com/info/release-end-of-life), the default should remain at 16.04. Instead, we can add a variant with: 
https://github.com/behance/docker-base/pull/28

**Comment by mayanand** [comment]
@bryanlatten Yeah the window is too narrow but one problem with adding a variant as in #24 is that we will have to support a third member to the family of BBCs apart from default Alpine and Ubuntu. Although we can cherrypick the BBCs for this variant and not support all of them.

**Comment by bryanlatten** [comment]
@mayanand agreed - this should be a limited-engagement BBC. No need for global support.
Call it "by need"

**Comment by mayanand** [comment]
@bryanlatten That makes sense. Closing this PR.

**Pull request closed without merging**
